name: muza_topup
description: "Muza Top-Up — PUBG Mobile UC & eFootball Coins top-up app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
